exclude: 'tools|local-setup|dnit|\.local|build|^terraform'
default_language_version:
  python: python3

repos:
  # typescript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.15.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@8.15.0
          - "@typescript-eslint/eslint-plugin@5.23.0"
          - "@typescript-eslint/parser@5.23.0"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
  # yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  # python
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        entry: isort -m VERTICAL_HANGING_INDENT --tc
        exclude: README.md
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
      # configuration is in pyproject.toml
      - id: mypy
        additional_dependencies:
          [types-requests, types-paramiko, types-python-dateutil]
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        types: [python]
        pass_filenames: true
        # require_serial: true
        additional_dependencies: ["pyright@1.1.226"]
